---
- hosts: omero
  
  tasks:
    - name: "{{ inventory_hostname }}"
      include_role:
        name: "{{ item }}"
      when: inventory_hostname == "omero-server"
      vars:
        roles:
          - ome.omero_server
        omero_server_dbhost: postgresql
        omero_server_dbname: omero
        omero_server_dbuser: omero
        omero_server_dbpass: omero
        postgresql_version: "14"
      loop: "{{ roles }}"
    - name: "{{ inventory_hostname }}"
      include_role:
        name: "{{ item }}"
      when: inventory_hostname == "omero-web"
      vars:
        roles:
          - ome.omero_web
      loop: "{{ roles }}"
    - name: "{{ inventory_hostname }}"
      include_role:
        name: "{{ item }}"
      when: inventory_hostname == "postgresql"
      vars:
        roles:
          - ome.postgresql
        postgresql_version: "14"
      loop: "{{ roles }}"
    
