---
- hosts: omero
  
  tasks:
    - name: "{{ inventory_hostname }}"
      include_role:
        name: ome.omero_server
      when: inventory_hostname == "omero-server"
      vars:
        ansible_become: true
        become_user: omero-server
        omero_server_dbhost:  postgresql
        postgresql_version: "14"
      timeout: 300
    - name: "{{ inventory_hostname }}"
      include_role:
        name: ome.postgresql
      when: inventory_hostname == "postgresql"
      vars:
        postgresql_version: "14"
        postgresql_server_listen: "'*'"
        postgresql_server_auth:
          - database: omero
            user: omero
            address: 0.0.0.0/0
        postgresql_databases:
          - name: omero
        postgresql_users:
          - user: omero
            password: omero
            databases: [omero]
    - name: "{{ inventory_hostname }}"
      include_role:
        name: "{{ item }}"
      when: inventory_hostname == "omero-web"
      vars:
        roles:
          - ome.basedeps
          - ome.omero_web
        omero_web_config_set:
          - omero.web.server_list: ['omero-server']
      loop: "{{ roles }}" 
