# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  boxes = [
    {
      :name => "ansible-host",
      :box => "debian/bookworm64",
      :ram => 4096,
      :vcpu => 1,
      :ip => "192.168.56.2"
    },
    {
      :name => "postgresql",
      :box => "rockylinux/9",
      :ram => 1024,
      :vcpu => 1,
      :ip => "192.168.56.3"
    },
    {
      :name => "omero-web",
      :box => "rockylinux/9",
      :ram => 1024,
      :vcpu => 1,
      :ip => "192.168.56.4"
    },
    {
      :name => "omero-server",
      :box => "rockylinux/9",
      :ram => 2048,
      :vcpu => 1,
      :ip => "192.168.56.5"
    }
  ]
  
  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.provision :shell, inline: <<-SHELL
      echo "#{opts[:ip]} #{opts[:name]}" >> /etc/hosts
    SHELL
    config.ssh.insert_key = false
    config.vm.define opts[:name] do |config|
      case opts[:name]
      when 'ansible-host'
        config.vm.synced_folder "./omero", "/home/vagrant/omero", id: "vagrant-root", disabled: false
      #   config.vm.provision :shell, inline: <<-SHELL
      #   ssh-keygen -t rsa -b 2048 -f /home/vagrant/.ssh/vagrant -C "vagrant@$(hostname)" -N ""
      #   chmod 600 /home/vagrant/.ssh/vagrant
      # SHELL
      end
      config.vm.box = opts[:box]
      config.vm.hostname = opts[:name]
      config.vm.provider :virtualbox do |v|
        v.memory = opts[:ram]
        v.cpus = opts[:vcpu]
      end
      config.vm.network :private_network, ip: opts[:ip]
      case opts[:name]
      when 'omero-server'
        config.vm.network :forwarded_port, guest: 4063, host: 4063
        config.vm.network :forwarded_port, guest: 4064, host: 4064
      when 'omero-web'
        config.vm.network :forwarded_port, guest: 80, host: 8080
        config.vm.network :forwarded_port, guest: 443, host:8443
      end
      config.vm.provision :file do |file|
        file.source = './config/vagrant.key.rsa'
        file.destination = '/tmp/vagrant'
      end
      # config.vm.provision :file do |file|
      #   file.source = './config/inventory.yaml'
      #   file.destination = '/home/vagrant/omero/inventory.yaml'
      # end
      config.vm.provision :file do |file|
        file.source = './config/ansible.cfg'
        file.destination = '/home/vagrant/.ansible.cfg'
      end
      config.vm.provision :ansible do |ansible|
        ansible.verbose = "vv"
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "./config/playbook.yaml"
      end
   end
  end
end
